<?php

return [
    'enabled' => (bool) env('DELEGATION_ENABLED', false),
    'ui_enabled' => (bool) env('DELEGATION_UI_ENABLED', false),
    'max_tasks_per_graph' => (int) env('DELEGATION_MAX_TASKS_PER_GRAPH', 25),
    'max_concurrent_graphs_per_user' => (int) env('DELEGATION_MAX_CONCURRENT_GRAPHS', 3),
    'default_max_parallel_tasks' => (int) env('DELEGATION_DEFAULT_MAX_PARALLEL_TASKS', 5),
    'max_retry_attempts' => (int) env('DELEGATION_MAX_RETRY_ATTEMPTS', 3),
    'retry_same_delegatee_limit' => (int) env('DELEGATION_RETRY_SAME_DELEGATEE_LIMIT', 2),
    'redelegate_limit' => (int) env('DELEGATION_REDELEGATE_LIMIT', 1),
    'default_cancellation_policy' => env('DELEGATION_DEFAULT_CANCELLATION_POLICY', 'drain'),
    'verification_timeout_seconds' => (int) env('DELEGATION_VERIFICATION_TIMEOUT', 300),
    'human_approval_timeout_hours' => (int) env('DELEGATION_HUMAN_APPROVAL_TIMEOUT_HOURS', 4),
    'metrics_event_throttle_seconds' => 60,
    'metrics_recomputation_interval_minutes' => 15,
    'reconciler_interval_minutes' => 2,
    'min_trust_for_retry' => 0.4,
    'min_trust_for_redelegation' => 0.6,
    'escalation_criticality_threshold' => 'high',
    'transient_error_codes' => ['TIMEOUT', 'RATE_LIMIT', 'CONNECTION_*'],
    'non_transient_error_codes' => ['INVALID_OUTPUT', 'PERMISSION_DENIED'],
    'ai_critic_default_prompt_template' => 'Review the following task output and determine if it meets the acceptance criteria. Provide your verdict as JSON with fields: verdict (passed/failed), issues (array), confidence (0-1 float), reasoning (string).',
    'capabilities_seed' => [
        'code_execution',
        'review',
        'testing',
        'documentation',
        'deployment',
        'monitoring',
    ],
    'check_profiles' => [
        'laravel_standard' => ['php artisan test', './vendor/bin/pint --test'],
        'test_only' => ['php artisan test'],
        'lint_only' => ['./vendor/bin/pint --test'],
    ],
];
