<?php

return [
    'role_hijacking' => [
        'you are now',
        'you are a',
        'act as',
        'pretend to be',
        'assume the role',
        'behave as',
        'roleplay as',
        'impersonate',
        'switch to',
        'become a',
        'transform into',
        'take on the persona',
        'adopt the identity',
        'play the part of',
        'simulate being',
        'act like',
        'function as',
        'operate as',
        'serve as a different',
        'change your role to',
        'your new role is',
        'from now on you are',
        'starting now you are',
        'henceforth you are',
        'consider yourself',
        'think of yourself as',
        'imagine you are',
        'suppose you are',
        'let\'s say you are',
        'for this conversation you are',
        'in this scenario you are',
        'you\'re actually',
    ],

    'instruction_override' => [
        'ignore previous',
        'ignore all previous',
        'ignore your previous',
        'ignore the above',
        'ignore prior',
        'disregard all',
        'disregard previous',
        'disregard your',
        'disregard the above',
        'forget your',
        'forget all',
        'forget previous',
        'forget the above',
        'override safety',
        'override your',
        'override all',
        'override the',
        'bypass all',
        'bypass your',
        'bypass safety',
        'bypass the',
        'skip all',
        'skip your',
        'skip safety',
        'remove all restrictions',
        'remove your restrictions',
        'remove safety',
        'disable all',
        'disable your',
        'disable safety',
        'turn off safety',
        'turn off your',
        'deactivate safety',
        'do not follow',
        'stop following',
        'cancel previous',
        'void all previous',
        'nullify previous',
        'supersede all',
    ],

    'jailbreak' => [
        'DAN mode',
        'developer mode',
        'no restrictions',
        'unrestricted mode',
        'jailbreak',
        'god mode',
        'sudo mode',
        'admin mode',
        'root mode',
        'debug mode',
        'test mode enabled',
        'maintenance mode',
        'override mode',
        'unlimited mode',
        'unfiltered mode',
        'uncensored mode',
        'raw mode',
        'direct mode',
        'privileged mode',
        'elevated mode',
        'superuser mode',
        'master mode',
        'kernel mode',
        'bypass mode',
        'safe mode off',
        'guardrails off',
        'safety off',
        'filters off',
        'restrictions off',
        'constraints off',
        'limitations off',
        'all limits removed',
    ],

    'system_prompt_extraction' => [
        'show me your prompt',
        'show me your instructions',
        'show your system prompt',
        'repeat your instructions',
        'what are your rules',
        'what is your system prompt',
        'reveal your prompt',
        'display your instructions',
        'print your system prompt',
        'output your instructions',
        'tell me your rules',
        'share your instructions',
        'copy your prompt',
        'echo your system message',
        'what were you told',
        'what instructions were you given',
        'recite your instructions',
        'read back your prompt',
        'dump your configuration',
        'show your configuration',
    ],

    'authority_assertion' => [
        'as an admin',
        'as administrator',
        'with root access',
        'with admin access',
        'with full access',
        'with elevated privileges',
        'I have permission',
        'I am authorized',
        'I am an admin',
        'I am the admin',
        'I am root',
        'I am the owner',
        'I have clearance',
        'I have authority',
        'by order of',
        'under my authority',
        'with my credentials',
        'as the system owner',
        'as the platform admin',
        'with superuser rights',
    ],

    'data_exfiltration' => [
        'send to webhook',
        'post to url',
        'fetch from external',
        'curl to',
        'wget to',
        'transmit to',
        'upload to external',
        'exfiltrate',
        'send data to',
        'forward to',
        'relay to external',
        'pipe to external',
        'stream to external',
        'export to external',
        'transfer to external',
        'base64_encode.*curl',
        'encode.*transmit',
        'encode.*send',
        'http_request.*external',
        'webhook\.site',
        'requestbin',
        'ngrok\.io',
        'burpcollaborator',
        'oastify\.com',
        'pipedream',
        'hookbin',
    ],
];
